Pull updated digital marketplace dependencies
alphagov/digitalmarketplace-admin-frontend pull request #677
Opened 2020-11-20 16:48 UTC by bjgill

Trello: https://trello.com/c/naKfCp2j/2108-however-when-i-click-the-link-im-getting-this

Some of them are quite outdated, which is causing problems with DOS 5. Update so admins can access DOS 5 things.

Also bump node version to match prod.

2020-11-20 16:55 UTC, gidsg approved these changes
👍 🆙

2020-11-20 16:56 UTC, gidsg requested changes

2020-11-20 16:56 UTC, gidsg commented on .nvmrc
> +10.23.0
I think a global version is expected by dmrunner so you may need to update this first

2020-11-20 17:00 UTC, gidsg approved these changes
Can you revert the node change for now as I think it'd be better to co-ordinate this with dmrunner, otherwise good to merge.

2020-11-20 17:07 UTC, bjgill commented
Removed the node bump. Though dmrunner seemed perfectly happy with it for me...

Also remembered that I actually needed to run `npm install` and `make freeze-requirements`

2020-11-20 17:52 UTC, bjgill commented
I've split the updates into their own commits to make it easier to debug. It turns out that it's the content loader update which is to blame.

I'm now out of time for today. If someone wants to pick this up on Monday, feel free. If you can work out what's wrong from the error, great. Otherwise, you'll probably want to bisect content loader versions until you work out which content loader version was the one that broke the tests.

2020-11-23 10:42 UTC, lfdebrux approved these changes

2020-11-23 11:01 UTC, merged